### ISSUE TITLE
Missing textures of certain mainframes

### ISSUE THREAD

**Issue by 905Sunny** [Jimbno/UU-Tex#11]
There are missing textures of mainframes in the patch of UU-Tex. Posting here because the patch page doesn't have an issues section

![2023-01-05_15 04 41](https://user-images.githubusercontent.com/44795811/210722555-6236e8be-e8c4-4b06-9d3d-b04b79fa2555.png)

**Comment by Hexakosioihexekontahexa** [comment]
@905Sunny, hello there. Fixed the issue, here's link to the latest release: https://github.com/Hexakosioihexekontahexa/UU-Tex/releases/tag/0.0.3.
Please note the new installation process. To install: **DELETE** previous version of patch and **COPY** or **MOVE** the archive into 'resourcepacks' folder onto client.
