### ISSUE TITLE
BOP flowers have broken textures

### ISSUE THREAD

**Issue by hallucinogender** [Jimbno/UU-Tex#2]
Flowers from Biomes O' Plenty have broken textures when using this texture pack. This is the case in dev version 29, I've not yet tested other versions. They appear to be displaying Railcraft tank textures.

**Comment by Ulire** [comment]
Delete the "minecraft" folder is work

**Comment by hallucinogender** [comment]
> Delete the "minecraft" folder is work

What purpose is this reply supposed to have? What relevance does it have to a bug report? I don't think there's any valid reason to clutter a development github page with comments that are not useful, relevant, or attempting to be either of those things.

**Comment by Ulire** [comment]
> > Delete the "minecraft" folder is work
> 
> What purpose is this reply supposed to have? What relevance does it have to a bug report? I don't think there's any valid reason to clutter a development github page with comments that are not useful, relevant, or attempting to be either of those things.

Are you sure......?
I mean delete the "UU-Tex/assets/minecraft" folder before you load this pack could fix the broken textures

**Comment by hallucinogender** [comment]
> Are you sure......? I mean delete the "UU-Tex/assets/minecraft" folder before you load this pack could fix the broken textures

I apologize, I misinterpreted your response as a meaningless comment suggesting I delete the game rather than ask for a bug to be fixed. If this method is functional as a fix then the issue can probably be closed.

**Comment by hallucinogender** [comment]
Update: deleting UU-Tex/assets/minecraft does _not_ function. The flowers still have broken textures.

**Comment by Ulire** [comment]
Okay, but the reason deleting the "minecraft" folder works is that the textures in that folder are incorrectly hardcoded to overwrite BoP's flower Id.
It did work in my case, maybe you need to reload the processed folder?

**Comment by Ulire** [comment]
[assets/minecraft/mcpatcher/ctm/Tanks/Aluminium/Casing/AluTank.properties](https://github.com/Jimbno/UU-Tex/blob/acae4e568291dc907e39d54c0d9c1a2131c7cb67/assets/minecraft/mcpatcher/ctm/Tanks/Aluminium/Casing/AluTank.properties)
This is one of hardcoded file paths that overwrite ID 1184.

**Comment by hallucinogender** [comment]
> Okay, but the reason deleting the "minecraft" folder works is that the textures in that folder are incorrectly hardcoded to overwrite BoP's flower Id. It did work in my case, maybe you need to reload the processed folder?

Reloading it worked. Thank you for the help.
